-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE)
FROM USED_GOODS_BOARD B
LEFT JOIN USED_GOODS_USER U
ON B.WRITER_ID=U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE) ASC;