-- 코드를 입력하세요
SELECT
    DATE_FORMAT(DATETIME, '%k') AS 'HOUR',
    COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') BETWEEN '09' AND '19'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H')