-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, ADDRESS, ROUND(AVG(W.REVIEW_SCORE), 2)
FROM REST_INFO AS I
INNER JOIN REST_REVIEW AS W
ON I.REST_ID = W.REST_ID
GROUP BY I.REST_ID
HAVING I.ADDRESS LIKE "서울%"
ORDER BY AVG(W.REVIEW_SCORE) DESC, FAVORITES DESC;